[nginx]
100.26.248.147 ansible_user=ubuntu ansible_ssh_private_key_file=~/viskey.pem

[appservers]
10.0.2.171 ansible_user=ubuntu ansible_ssh_private_key_file=~/viskey.pem
10.0.2.62 ansible_user=ubuntu ansible_ssh_private_key_file=~/viskey.pem

[appservers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -i ~/viskey.pem -W %h:%p ubuntu@100.26.248.147"'
